# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Runtime演示1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Runtime演示1
  # 指定库 和 库的版本
  pod 'AFNetworking',  '~> 3.1.0'
  pod  'SDWebImage',   '~> 4.2.2'



end
